---
abstract: Catalyst wxPerl Engine
author: 'Eriam Schaffter <eriam@cpan.org>'
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Engine-Wx
no_index:
  directory:
    - inc
    - t
requires:
  Alien::wxWidgets: 0
  Catalyst: 0
  Class::Inspector: 0
  Module::Reload: 0
  POE: 0.38
  Wx: 0
version: 0.02_02
