--- #YAML:1.0
name:                Catalyst-Engine-Wx
version:             0.02_04
abstract:            Catalyst wxPerl Engine
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Alien::wxWidgets:              0
    Catalyst:                      0
    Class::Inspector:              0
    Module::Reload:                0
    POE:                           0.38
    POE::Loop::Wx:                 0.03
    Test::More:                    0
    version:                       0
    Wx:                            0.67
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Eriam Schaffter <eriam@cpan.org>
